  - name: workstation set up
    hosts: localhost
    become: yes
    tasks:
      - name: Memory good
        ansible.builtin.debug:
          msg: Memory is good
        when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 < 50

