  - name: workstation set up
    hosts: localhost
    become: yes
    tasks:
      - name: Memory good
        ansible.builtin.debug:
          msg: Memory is good i.e green
        when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 < 75

      - name: Memory orange
        ansible.builtin.debug:
          msg: Memory is in yellow
        when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 > 75 && ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 < 50

      - name: Memory red
        ansible.builtin.debug:
          msg: Memory is in red
        when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 > 50