- name: Demo on vars
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print the task variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: task.example.com

    - name: Print the play variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: play.example.com

    - name: Print the variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
